name: Bounty
main: it.scampiaparty.bounty.Main
version: 1.0
api-version: 1.8
commands:
  bounty:
    description: Metti una bounty
  bountystatus:
    description: Controlla le bounty
permissions:
  bounty.use:
    default: true
