name: Build Plugins

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        for d in */ ; do
          if [ -f "$d/pom.xml" ]; then
            echo "Building $d"
            cd "$d"
            mvn -B package --file pom.xml
            cd ..
          fi
        done

    - name: Upload jars
      uses: actions/upload-artifact@v3
      with:
        name: plugin-jars
        path: '**/target/*.jar'
