name: Build Plugins

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    # Step di debug per controllare la struttura delle cartelle
    - name: List repository structure
      run: ls -R

    - name: Build all plugins
      run: |
        for d in */ ; do
          if [ -f "$d/pom.xml" ]; then
            echo "Building $d"
            cd "$d"
            mvn -B package --file pom.xml
            cd ..
          else
            echo "No pom.xml found in $d, skipping..."
          fi
        done

    - name: Upload JARs
      uses: actions/upload-artifact@v4
      with:
        name: plugin-jars
        path: ./**/target/*.jar
